import type { LibraryItem } from "./App";

// Personal demo seed — committed to the repo alongside public/seed-demo/.
// Images in public/seed-demo/ are compressed by hand to keep the folder
// small; keep filenames stable and match mediaWidth/mediaHeight to the files.
// Served from public/seed-demo/. To restore the original demo library, flip
// `demoSeedItems` back to `seedItems` in App.tsx and delete this file.
export const personalSeedItems: LibraryItem[] = [
  {
    id: "me-fuji-night",
    kind: "Image",
    title: "Fuji over the village lights",
    description: "Nightfall with the town glowing below the mountain.",
    source: "Downloads",
    date: "Saved today",
    tags: ["photography", "japan", "landscape"],
    image: "/seed-demo/compressO-6248AFB9-CEA1-45EE-944A-06CD88501EF8.jpg",
    sourceUrl: "/seed-demo/compressO-6248AFB9-CEA1-45EE-944A-06CD88501EF8.jpg",
    mediaWidth: 4000,
    mediaHeight: 6000,
    imageAlt: "Mount Fuji at night above a village glowing with lights",
    featured: true,
    favorite: true,
  },
  {
    id: "me-spidey-rain",
    kind: "Image",
    title: "Spider-Man in the rain",
    description: "Crouched on a gargoyle, rain coming down hard.",
    source: "Downloads",
    date: "Saved today",
    tags: ["comics", "wallpaper"],
    image: "/seed-demo/compressO-IMG_4631.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_4631.jpg",
    mediaWidth: 1080,
    mediaHeight: 1346,
    imageAlt: "Spider-Man crouching in the rain in a comic-book illustration",
    favorite: true,
  },
  {
    id: "me-lanterns",
    kind: "Image",
    title: "Lanterns outside the izakaya",
    description: "Warm paper lanterns on a dark Tokyo street.",
    source: "Downloads",
    date: "Yesterday",
    tags: ["photography", "japan", "night"],
    image: "/seed-demo/compressO-6270CBFE-632E-481D-BBE4-D1654635C2E8.jpg",
    sourceUrl: "/seed-demo/compressO-6270CBFE-632E-481D-BBE4-D1654635C2E8.jpg",
    mediaWidth: 6000,
    mediaHeight: 4000,
    imageAlt: "Glowing Japanese lanterns outside a restaurant at night",
  },
  {
    id: "me-blossoms",
    kind: "Image",
    title: "Cherry blossoms, close up",
    description: "Full bloom, almost too pink to be real.",
    source: "Downloads",
    date: "Yesterday",
    tags: ["photography", "spring"],
    image: "/seed-demo/compressO-6E4DB3C2-1738-4956-B1EA-F7B118DA49FD.jpg",
    sourceUrl: "/seed-demo/compressO-6E4DB3C2-1738-4956-B1EA-F7B118DA49FD.jpg",
    mediaWidth: 4000,
    mediaHeight: 6000,
    imageAlt: "Close-up of bright pink cherry blossoms on a branch",
    favorite: true,
  },
  {
    id: "me-clip",
    kind: "Video",
    title: "Saved clip",
    description: "A 10-second clip from my downloads.",
    source: "Downloads",
    date: "Yesterday",
    tags: ["video"],
    fileUrl: "/seed-demo/saved-clip.mp4",
    sourceUrl: "/seed-demo/saved-clip.mp4",
    mediaWidth: 1280,
    mediaHeight: 720,
    imageAlt: "A saved video clip",
  },
  {
    id: "me-fuji-maple",
    kind: "Image",
    title: "Fuji through red maples",
    description: "Autumn framing the mountain perfectly.",
    source: "Downloads",
    date: "Sep 11",
    tags: ["photography", "japan", "landscape"],
    image: "/seed-demo/compressO-BE4813D8-0629-4E79-8DB4-E32B76874B84.jpg",
    sourceUrl: "/seed-demo/compressO-BE4813D8-0629-4E79-8DB4-E32B76874B84.jpg",
    mediaWidth: 3837,
    mediaHeight: 5756,
    imageAlt: "Mount Fuji seen through red autumn maple leaves",
  },
  {
    id: "me-anime-girl",
    kind: "Image",
    title: "Uniform sketch",
    description: "Blonde anime character in a school uniform.",
    source: "Downloads",
    date: "Sep 11",
    tags: ["anime", "illustration"],
    image: "/seed-demo/compressO-IMG_3865.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_3865.jpg",
    mediaWidth: 1080,
    mediaHeight: 1920,
    imageAlt: "Anime illustration of a blonde girl in a school uniform",
  },
  {
    id: "me-shoreline",
    kind: "Image",
    title: "Where the waves land",
    description: "Aerial shot of surf washing over dark sand.",
    source: "Downloads",
    date: "Sep 10",
    tags: ["photography", "ocean", "aerial"],
    image: "/seed-demo/compressO-D7CF964F-BD6F-427D-BABC-DAF4A39FAAB8.jpg",
    sourceUrl: "/seed-demo/compressO-D7CF964F-BD6F-427D-BABC-DAF4A39FAAB8.jpg",
    mediaWidth: 2334,
    mediaHeight: 2917,
    imageAlt: "Aerial view of ocean waves washing over a shoreline",
  },
  {
    id: "me-optimus",
    kind: "Image",
    title: "Optimus Prime",
    description: "Battle-worn and glowing.",
    source: "Downloads",
    date: "Sep 10",
    tags: ["movies", "poster", "reference"],
    image: "/seed-demo/compressO-IMG_4633.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_4633.jpg",
    mediaWidth: 640,
    mediaHeight: 960,
    imageAlt: "Optimus Prime from Transformers surrounded by firelight",
  },
  {
    id: "me-canyon",
    kind: "Image",
    title: "Red rock country",
    description: "Ochre cliffs and scrub, somewhere dry and quiet.",
    source: "Downloads",
    date: "Sep 09",
    tags: ["photography", "landscape"],
    image: "/seed-demo/compressO-F5D0F587-A884-4510-BCE5-4D0E04308D62.jpg",
    sourceUrl: "/seed-demo/compressO-F5D0F587-A884-4510-BCE5-4D0E04308D62.jpg",
    mediaWidth: 4000,
    mediaHeight: 6000,
    imageAlt: "Red and orange rock formations in a desert canyon",
  },
  {
    id: "me-batman",
    kind: "Image",
    title: "Batman on the bike",
    description: "Minimal poster, all ink and red.",
    source: "Downloads",
    date: "Sep 09",
    tags: ["movies", "poster", "reference"],
    image: "/seed-demo/compressO-IMG_4634.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_4634.jpg",
    mediaWidth: 1080,
    mediaHeight: 1920,
    imageAlt: "Stylized Batman motorcycle poster with vertical title text",
  },
  {
    id: "me-branch",
    kind: "Image",
    title: "First blossom",
    description: "One white branch against the green blur.",
    source: "Downloads",
    date: "Sep 08",
    tags: ["photography", "spring"],
    image: "/seed-demo/compressO-9BCD88C1-AFC4-483B-9A33-7C6F292BFBB2.jpg",
    sourceUrl: "/seed-demo/compressO-9BCD88C1-AFC4-483B-9A33-7C6F292BFBB2.jpg",
    mediaWidth: 2832,
    mediaHeight: 4248,
    imageAlt: "A branch of small white blossoms against a soft green background",
  },
  {
    id: "me-anime-boy",
    kind: "Image",
    title: "Track jacket",
    description: "Anime character adjusting his collar.",
    source: "Downloads",
    date: "Sep 08",
    tags: ["anime", "illustration"],
    image: "/seed-demo/compressO-IMG_3921.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_3921.jpg",
    mediaWidth: 1200,
    mediaHeight: 1991,
    imageAlt: "Anime illustration of a boy in a black and orange track jacket",
  },
  {
    id: "me-building",
    kind: "Image",
    title: "The brick corner",
    description: "A historic corner building looking over the street.",
    source: "Downloads",
    date: "Sep 07",
    tags: ["photography", "architecture", "city"],
    image: "/seed-demo/compressO-A247AFD7-6871-4B6B-98B7-CDD69736409F.jpg",
    sourceUrl: "/seed-demo/compressO-A247AFD7-6871-4B6B-98B7-CDD69736409F.jpg",
    mediaWidth: 3930,
    mediaHeight: 5895,
    imageAlt: "A historic brick corner building in a city street",
  },
  {
    id: "me-spidey-mask",
    kind: "Image",
    title: "Eye lenses",
    description: "Extreme close-up on the mask.",
    source: "Downloads",
    date: "Sep 07",
    tags: ["movies", "wallpaper"],
    image: "/seed-demo/compressO-IMG_4632.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_4632.jpg",
    mediaWidth: 623,
    mediaHeight: 1350,
    imageAlt: "Close-up of Spider-Man's mask and eye lens",
  },
  {
    id: "me-valley",
    kind: "Image",
    title: "River through the valley",
    description: "Green ridges and a winding river below.",
    source: "Camera roll",
    date: "Sep 06",
    tags: ["photography", "landscape"],
    image: "/seed-demo/compressO-IMG_2618.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_2618.jpg",
    mediaWidth: 1080,
    mediaHeight: 1920,
    imageAlt: "A river winding through a green mountain valley",
  },
  {
    id: "me-fort",
    kind: "Image",
    title: "The fort on the water",
    description: "Stone walls right at the edge of the sea.",
    source: "Downloads",
    date: "Sep 05",
    tags: ["photography", "travel"],
    image: "/seed-demo/compressO-BD0448C2-54B5-4791-B6EF-05629CA6C40C.jpg",
    sourceUrl: "/seed-demo/compressO-BD0448C2-54B5-4791-B6EF-05629CA6C40C.jpg",
    mediaWidth: 1967,
    mediaHeight: 2934,
    imageAlt: "A historic stone fort sitting in the sea near the shore",
  },
  {
    id: "me-mockups",
    kind: "Image",
    title: "Music app screens",
    description: "Five phone mockups with different player themes.",
    source: "Camera roll",
    date: "Sep 05",
    tags: ["ui", "reference", "design"],
    image: "/seed-demo/compressO-IMG_4637.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_4637.jpg",
    mediaWidth: 2000,
    mediaHeight: 2000,
    imageAlt: "Five phone mockups showing colorful music player designs",
  },
  {
    id: "me-cliffs",
    kind: "Image",
    title: "Cliffs at golden hour",
    description: "The coast glowing before sunset.",
    source: "Downloads",
    date: "Sep 04",
    tags: ["photography", "ocean", "travel"],
    image: "/seed-demo/compressO-D2BD78FD-1D0F-4124-BAF0-C65065F12791.jpg",
    sourceUrl: "/seed-demo/compressO-D2BD78FD-1D0F-4124-BAF0-C65065F12791.jpg",
    mediaWidth: 4000,
    mediaHeight: 6000,
    imageAlt: "Sunlit coastal cliffs above the ocean at sunset",
  },
  {
    id: "me-shark",
    kind: "Image",
    title: "Shark, passing by",
    description: "Underwater and unbothered.",
    source: "Camera roll",
    date: "Sep 03",
    tags: ["photography", "ocean", "wildlife"],
    image: "/seed-demo/compressO-IMG_4635.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_4635.jpg",
    mediaWidth: 736,
    mediaHeight: 1308,
    imageAlt: "A shark swimming underwater",
  },
  {
    id: "me-silk",
    kind: "Image",
    title: "Black silk",
    description: "Dark abstract wallpaper material.",
    source: "Camera roll",
    date: "Sep 02",
    tags: ["abstract", "wallpaper"],
    image: "/seed-demo/compressO-IMG_4630.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_4630.jpg",
    mediaWidth: 650,
    mediaHeight: 1156,
    imageAlt: "Abstract black silk-like waves",
  },
  {
    id: "me-film-still",
    kind: "Image",
    title: "Period film still",
    description: "Three men in vintage dress, mid-conversation.",
    source: "Camera roll",
    date: "Sep 01",
    tags: ["movies", "reference"],
    image: "/seed-demo/compressO-IMG_4636.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_4636.jpg",
    mediaWidth: 736,
    mediaHeight: 485,
    imageAlt: "Three men in period costume standing outdoors in a film still",
  },
  {
    id: "me-icons",
    kind: "Image",
    title: "Icon set exploration",
    description: "Weather and action icons in a few colorways.",
    source: "Camera roll",
    date: "Aug 30",
    tags: ["ui", "reference", "design"],
    image: "/seed-demo/compressO-IMG_4638.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_4638.jpg",
    mediaWidth: 1200,
    mediaHeight: 672,
    imageAlt: "A grid of app icons in different styles and colors",
  },
  {
    id: "me-f1",
    kind: "Image",
    title: "Remaining races",
    description: "Night-race graphic counting down the season.",
    source: "Camera roll",
    date: "Aug 28",
    tags: ["racing", "reference", "design"],
    image: "/seed-demo/compressO-IMG_4640.jpg",
    sourceUrl: "/seed-demo/compressO-IMG_4640.jpg",
    mediaWidth: 1080,
    mediaHeight: 1350,
    imageAlt: "A night racing graphic reading remaining races",
  },
];
